name: scanner
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.4.2
  auto_route_generator: ^2.4.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter_hooks: ^0.18.2
  modal_progress_hud: ^0.1.3
  data_connection_checker: ^0.3.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  scan: ^1.6.0
  font_awesome_flutter: ^9.2.0
  flutter_beep: ^1.0.0
  flutter_screenutil: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.0
  font_awesome: ^5.10.1
  hive_generator: ^1.1.2
  flutter_launcher_icons: ^0.9.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove
  color: "#49a0ae"
  image: assets/images/splash.png
  android_gravity: fill
  ios_content_mode: scaleToFill

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
